server:
  PORT: 5000
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://awseb-e-kx2kbwprca-stack-awsebrdsdatabase-5jjj7hmkl2dm.cojux4aissck.ap-northeast-2.rds.amazonaws.com:3306/ebdb
    username: ${rds.username}
    password: ${rds.password}
